package netcheck

import (
	"reflect"
	"strings"
	"testing"
)

func TestParseResolvConf(t *testing.T) {
	in := `# Generated by NetworkManager
search corp.example
nameserver 10.4.60.100
nameserver 10.4.60.101 # trailing comment
options edns0
nameserver not-an-ip
`
	got := parseResolvConf(strings.NewReader(in))
	want := []string{"10.4.60.100", "10.4.60.101"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("parseResolvConf = %v, want %v", got, want)
	}
}

func TestAllLoopback(t *testing.T) {
	if !allLoopback([]string{"127.0.0.53"}) {
		t.Error("a lone systemd-resolved stub must count as loopback")
	}
	if allLoopback([]string{"127.0.0.53", "10.4.60.100"}) {
		t.Error("a real upstream next to the stub must not count as loopback")
	}
	if allLoopback(nil) {
		t.Error("no servers must not count as loopback")
	}
}
