package cmd

import (
	"fmt"

	"github.com/spf13/cobra"
)

var shellInitCmd = &cobra.Command{
	Use:   "shell-init",
	Short: "Output shell integration code (source once in .zshrc / .bashrc)",
	Long: `Outputs a shell function that wraps hopscotch enable/disable with automatic
eval, and prepends the proxy icon to your prompt.

Add to your ~/.zshrc or ~/.bashrc:

  eval "$(hopscotch shell-init)"

Then use without eval:

  hopscotch enable
  hopscotch disable`,
	RunE: runShellInit,
}

func init() {
	rootCmd.AddCommand(shellInitCmd)
}

// shellInitScript is sourced by the user's shell. It:
//   - wraps enable/disable with auto-eval so no manual eval $() is needed
//   - prepends ${HOPSCOTCH_ACTIVE} to PROMPT/PS1 (expands dynamically, no restart needed)
const shellInitScript = `# hopscotch shell integration — generated by: hopscotch shell-init
hopscotch() {
  case "${1:-}" in
    enable|disable)
      eval "$(command hopscotch "$@")"
      ;;
    *)
      command hopscotch "$@"
      ;;
  esac
}
# Prepend proxy icon to prompt on every command via precmd hook.
# Runs after theme hooks (p10k, oh-my-zsh) since we're added last.
if [ -n "${ZSH_VERSION:-}" ]; then
  autoload -Uz add-zsh-hook
  _hopscotch_precmd() {
    [[ -n "${HOPSCOTCH_ACTIVE:-}" ]] && PROMPT="${HOPSCOTCH_ACTIVE} ${PROMPT}"
  }
  add-zsh-hook precmd _hopscotch_precmd
elif [ -n "${BASH_VERSION:-}" ]; then
  _hopscotch_precmd() {
    [[ -n "${HOPSCOTCH_ACTIVE:-}" && "$PS1" != *"${HOPSCOTCH_ACTIVE}"* ]] && PS1="${HOPSCOTCH_ACTIVE} ${PS1}"
  }
  PROMPT_COMMAND="_hopscotch_precmd${PROMPT_COMMAND:+; $PROMPT_COMMAND}"
fi`

func runShellInit(_ *cobra.Command, _ []string) error {
	fmt.Println(shellInitScript)
	return nil
}
