package cmd

import (
	"fmt"

	"github.com/spf13/cobra"
)

var shellInitCmd = &cobra.Command{
	Use:   "shell-init",
	Short: "Output shell integration code (source once in .zshrc / .bashrc)",
	Long: `Outputs a shell function that wraps hopscotch enable/disable with automatic
eval, and prepends the proxy icon to your prompt.

Add to your ~/.zshrc or ~/.bashrc:

  eval "$(hopscotch shell-init)"

Then use without eval:

  hopscotch enable
  hopscotch disable`,
	RunE: runShellInit,
}

func init() {
	rootCmd.AddCommand(shellInitCmd)
}

// shellInitScript is sourced by the user's shell. It:
//   - wraps enable/disable with auto-eval so no manual eval $() is needed
//   - prepends ${HOPSCOTCH_ACTIVE} to PROMPT/PS1 (expands dynamically, no restart needed)
const shellInitScript = `# hopscotch shell integration — generated by: hopscotch shell-init
export HOPSCOTCH_SHELL_INIT=1
hopscotch() {
  case "${1:-}" in
    enable|disable)
      eval "$(command hopscotch "$@")"
      ;;
    *)
      command hopscotch "$@"
      ;;
  esac
}`

func runShellInit(_ *cobra.Command, _ []string) error {
	fmt.Println(shellInitScript)
	return nil
}
