package cmd

import (
	"bufio"
	"fmt"
	"os"
	"strings"

	"github.com/charmbracelet/log"
	"github.com/spf13/cobra"

	"hopscotch/internal/config"
	"hopscotch/internal/proxy"
)

var sshConfigWrite bool

var sshConfigCmd = &cobra.Command{
	Use:   "ssh-config",
	Short: "Print SSH config block that routes matching hosts via hopscotch",
	Long: `Prints an SSH config snippet that routes matching hosts through
hopscotch's SOCKS5 proxy using ProxyCommand.

Pipe into your SSH config:

  hopscotch ssh-config >> ~/.ssh/config

Or write to a separate file and include it:

  hopscotch ssh-config --write
  echo 'Include ~/.config/hopscotch/ssh_config' >> ~/.ssh/config`,
	RunE: runSSHConfig,
}

func init() {
	sshConfigCmd.Flags().BoolVar(&sshConfigWrite, "write", false, "write to ~/.config/hopscotch/ssh_config instead of stdout")
	rootCmd.AddCommand(sshConfigCmd)
}

func runSSHConfig(_ *cobra.Command, _ []string) error {
	cfg, err := config.Load(configPath)
	if err != nil {
		return err
	}

	out := buildSSHConfig(cfg)

	if sshConfigWrite {
		home, err := os.UserHomeDir()
		if err != nil {
			return err
		}
		dir := home + "/.config/hopscotch"
		path := dir + "/ssh_config"
		if err := os.MkdirAll(dir, 0o700); err != nil {
			return fmt.Errorf("creating config dir: %w", err)
		}
		if err := os.WriteFile(path, []byte(out), 0o600); err != nil {
			return fmt.Errorf("writing ssh config: %w", err)
		}
		fmt.Printf("Written to %s\n\n", path)
		printSSHConfigSummary(cfg)
		if err := ensureSSHInclude(path); err != nil {
			return err
		}
		return nil
	}

	fmt.Print(out)
	return nil
}

func printSSHConfigSummary(cfg *config.Config) {
	tunnelPatterns := map[string][]string{}
	for _, rule := range cfg.Proxy.Rules {
		if rule.Tunnel != "" {
			tunnelPatterns[rule.Tunnel] = append(tunnelPatterns[rule.Tunnel], rule.Pattern)
		}
	}
	for _, t := range cfg.Tunnels {
		patterns, ok := tunnelPatterns[t.Name]
		if !ok {
			continue
		}
		fmt.Printf("  %-24s → %s\n", t.Name, strings.Join(patterns, ", "))
	}
	fmt.Println()
}

// ensureSSHInclude checks whether ~/.ssh/config already includes path.
// If not, it asks the user and appends the Include line on confirmation.
func ensureSSHInclude(path string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	sshConfig := home + "/.ssh/config"
	includeLine := "Include " + path

	// Check if the include is already present.
	data, err := os.ReadFile(sshConfig)
	if err == nil && strings.Contains(string(data), includeLine) {
		fmt.Println("~/.ssh/config already includes hopscotch ssh_config — nothing to do.")
		return nil
	}

	fmt.Printf("Add the following to ~/.ssh/config?\n\n    %s\n\n[y/N] ", includeLine)
	var answer string
	fmt.Fscan(bufio.NewReader(os.Stdin), &answer)
	if strings.ToLower(strings.TrimSpace(answer)) != "y" {
		fmt.Printf("\nRun manually when ready:\n\n    echo '%s' >> ~/.ssh/config\n", includeLine)
		return nil
	}

	f, err := os.OpenFile(sshConfig, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o600)
	if err != nil {
		return fmt.Errorf("opening ~/.ssh/config: %w", err)
	}
	defer f.Close()
	if _, err := fmt.Fprintf(f, "\n%s\n", includeLine); err != nil {
		return fmt.Errorf("writing to ~/.ssh/config: %w", err)
	}
	fmt.Println("\nAdded. SSH will now route matching hosts via hopscotch.")
	return nil
}

// refreshSSHConfig rewrites ~/.config/hopscotch/ssh_config if it already exists.
// Called automatically on config reload; skipped if the file was never written.
func refreshSSHConfig(cfg *config.Config) {
	home, err := os.UserHomeDir()
	if err != nil {
		return
	}
	path := home + "/.config/hopscotch/ssh_config"
	if _, err := os.Stat(path); err != nil {
		return // file not present — user hasn't opted in yet
	}
	if err := os.WriteFile(path, []byte(buildSSHConfig(cfg)), 0o600); err != nil {
		log.Error("failed to refresh ssh_config", "path", path, "err", err)
		return
	}
	log.Info("ssh_config refreshed", "path", path)
}

func buildSSHConfig(cfg *config.Config) string {
	var sb strings.Builder

	home, _ := os.UserHomeDir()
	sb.WriteString("# Generated by hopscotch ssh-config\n")
	sb.WriteString("# To keep this up to date, use:\n")
	sb.WriteString("#\n")
	sb.WriteString("#   hopscotch ssh-config --write\n")
	sb.WriteString(fmt.Sprintf("#   Include %s/.config/hopscotch/ssh_config\n", home))
	sb.WriteString("\n")

	// Map tunnel name → glob patterns and CIDR blocks separately.
	// CIDR blocks cannot be expressed as SSH Host patterns, so they are
	// noted as comments; use Match originalhost for named aliases instead.
	type tunnelEntries struct {
		globs []string
		cidrs []string
	}
	entries := map[string]*tunnelEntries{}
	for _, rule := range cfg.Proxy.Rules {
		if rule.Tunnel == "" {
			continue
		}
		if entries[rule.Tunnel] == nil {
			entries[rule.Tunnel] = &tunnelEntries{}
		}
		if proxy.IsCIDR(rule.Pattern) {
			entries[rule.Tunnel].cidrs = append(entries[rule.Tunnel].cidrs, rule.Pattern)
		} else {
			entries[rule.Tunnel].globs = append(entries[rule.Tunnel].globs, rule.Pattern)
		}
	}

	for _, t := range cfg.Tunnels {
		e, ok := entries[t.Name]
		if !ok {
			continue
		}
		sb.WriteString(fmt.Sprintf("# tunnel: %s → localhost:%d\n", t.Name, t.LocalPort))
		if len(e.cidrs) > 0 {
			sb.WriteString(fmt.Sprintf("# CIDR rules (not SSH Host syntax — cover with Match originalhost): %s\n",
				strings.Join(e.cidrs, " ")))
		}
		if len(e.globs) > 0 {
			sb.WriteString(fmt.Sprintf("Host %s\n", strings.Join(e.globs, " ")))
			sb.WriteString("    ProxyCommand hopscotch proxy-connect %h %p\n")
		}
		sb.WriteString("\n")
	}

	return sb.String()
}
