package config

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"

	"gopkg.in/yaml.v3"
)

const writeHeader = "# Generated by hopscotch — manual edits will be overwritten on next save\n\n"

var ruleItemRe = regexp.MustCompile(`\n([ \t]+- pattern:)`)

// WriteConfig serializes cfg to YAML and atomically writes it to path.
// Original file comments are lost; a generated header is prepended.
// Rule blocks are separated by blank lines for readability.
func WriteConfig(cfg *Config, path string) error {
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("serializing config: %w", err)
	}
	data = insertRuleSpacing(data)
	out := append([]byte(writeHeader), data...)

	tmp, err := os.CreateTemp(filepath.Dir(path), ".hopscotch-*.yaml.tmp")
	if err != nil {
		return fmt.Errorf("creating temp file: %w", err)
	}
	tmpPath := tmp.Name()
	defer func() {
		tmp.Close()
		os.Remove(tmpPath) // no-op if rename succeeded
	}()

	if _, err := tmp.Write(out); err != nil {
		return fmt.Errorf("writing config: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("flushing config: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("replacing config file: %w", err)
	}
	return nil
}

// insertRuleSpacing adds a blank line before each rule block (except the first)
// so the serialized YAML is easier to read.
func insertRuleSpacing(data []byte) []byte {
	first := true
	return ruleItemRe.ReplaceAllFunc(data, func(match []byte) []byte {
		if first {
			first = false
			return match
		}
		return append([]byte("\n"), match...)
	})
}
