package vpn

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

// hopscotch hands openconnect its own vpnc-script wrapper (--script). The
// wrapper runs the system vpnc-script as before and then fixes the two things
// that make switching between VPNs into the same network unpredictable:
//
//   - on connect every pushed route is (re)pointed at this session's tunnel
//     (`ip route replace` / `route change`), so the session that came up last
//     carries the traffic on macOS too, where the system script's `route add`
//     fails with "File exists" while another VPN holds the route;
//   - on disconnect only routes still on this tunnel are removed, and routes
//     belonging to another VPN that is still up are put back (the system
//     script on macOS deletes by prefix, which would take the other VPN's
//     routes with it).
//
// It also records what the gateway pushed (routes, DNS, address) in a small
// JSON file next to the session history, which hopscotch reads for /status
// (see pushed.go). One wrapper per VPN, regenerated on every start, so no
// arguments or environment need to survive sudo.

// systemVPNCScriptCandidates are the usual locations of the vpnc-script that
// openconnect is built to use, most specific first.
var systemVPNCScriptCandidates = map[string][]string{
	"darwin": {
		"/opt/homebrew/etc/vpnc/vpnc-script",
		"/usr/local/etc/vpnc/vpnc-script",
		"/etc/vpnc/vpnc-script",
	},
	"linux": {
		"/etc/vpnc/vpnc-script",
		"/usr/share/vpnc-scripts/vpnc-script",
		"/usr/local/etc/vpnc/vpnc-script",
	},
}

// findSystemVPNCScript returns the system vpnc-script the wrapper should call,
// or "" when none is found (openconnect then gets a wrapper that only records
// and fixes routes — the same as running openconnect with no script at all,
// which it warns about).
func findSystemVPNCScript() string {
	for _, p := range systemVPNCScriptCandidates[runtime.GOOS] {
		if st, err := os.Stat(p); err == nil && !st.IsDir() {
			return p
		}
	}
	return ""
}

// wrapperFileName is the per-VPN wrapper script in the cache directory.
func wrapperFileName(vpnName string) string { return "vpnc-" + safeFileName(vpnName) + ".sh" }

// pushedFileName is the per-VPN JSON the wrapper writes on connect.
func pushedFileName(vpnName string) string { return "vpn-" + safeFileName(vpnName) + ".pushed.json" }

// safeFileName keeps VPN names usable as file names.
func safeFileName(name string) string {
	return strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '-', r == '_', r == '.':
			return r
		}
		return '_'
	}, name)
}

// writeVPNCWrapper (re)writes the wrapper for vpnName in dir and returns its
// path. systemScript may be "".
func writeVPNCWrapper(dir, vpnName, systemScript string) (string, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, wrapperFileName(vpnName))
	body := renderVPNCWrapper(vpnName, systemScript, dir)
	if err := os.WriteFile(path, []byte(body), 0o755); err != nil {
		return "", err
	}
	// WriteFile keeps an existing file's mode; make sure it is executable.
	if err := os.Chmod(path, 0o755); err != nil {
		return "", err
	}
	return path, nil
}

// renderVPNCWrapper fills the wrapper template. Values are single-quoted for
// sh; a quote in a value (impossible for the generated paths, unlikely for a
// VPN name) is escaped.
func renderVPNCWrapper(vpnName, systemScript, dir string) string {
	q := func(s string) string { return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'" }
	r := strings.NewReplacer(
		"@@VPN@@", q(vpnName),
		"@@SYSTEM_SCRIPT@@", q(systemScript),
		"@@STATE_FILE@@", q(filepath.Join(dir, pushedFileName(vpnName))),
		"@@STATE_GLOB@@", q(filepath.Join(dir, "vpn-"))+`'*.pushed.json'`,
		"@@TRACE_FILE@@", q(filepath.Join(dir, "vpnc-"+safeFileName(vpnName)+".log")),
		"@@HEADER@@", fmt.Sprintf("Generated by hopscotch for VPN %q; rewritten on every start, do not edit.", vpnName),
	)
	return r.Replace(vpncWrapperTemplate)
}

// vpncWrapperTemplate is POSIX sh: openconnect runs the script as root through
// sudo, on macOS with /bin/sh, so nothing bash-specific.
const vpncWrapperTemplate = `#!/bin/sh
# @@HEADER@@
#
# Runs the system vpnc-script, then makes sure every route the gateway pushed
# points at this session's tunnel, and on disconnect removes only this
# tunnel's routes while putting back those of any other VPN still up. Records
# what was pushed in a JSON file hopscotch reads.
VPN=@@VPN@@
SYSTEM_SCRIPT=@@SYSTEM_SCRIPT@@
STATE_FILE=@@STATE_FILE@@
STATE_GLOB=@@STATE_GLOB@@
TRACE_FILE=@@TRACE_FILE@@

OS=${HOPSCOTCH_WRAPPER_OS:-$(uname -s)}

# A one-line-per-run trace (one file per VPN, appended, emptied past 256 KB)
# with the default route before and after — enough to see if a run lost it,
# without the noise of every route command.
default_route() {
	if [ "$OS" = Darwin ]; then
		netstat -rn -f inet 2>/dev/null | awk '$1=="default" && $NF!~/^bridge/ {print $2" "$NF; exit}'
	else
		ip route show default 2>/dev/null | head -1
	fi
}
trace() {
	[ -f "$TRACE_FILE" ] && [ "$(wc -c <"$TRACE_FILE" 2>/dev/null)" -gt 262144 ] && : >"$TRACE_FILE"
	printf '%s reason=%-18s tundev=%-6s default=[%s] %s\n' \
		"$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$reason" "$TUNDEV" "$(default_route)" "$1" >>"$TRACE_FILE"
}
trace before

if [ -n "$SYSTEM_SCRIPT" ] && [ -x "$SYSTEM_SCRIPT" ]; then
	"$SYSTEM_SCRIPT"
fi
trace after-system-script

# pushed_routes prints each split-include network as addr/len, one per line.
pushed_routes() {
	i=0
	while [ "$i" -lt "${CISCO_SPLIT_INC:-0}" ]; do
		eval addr=\"\${CISCO_SPLIT_INC_${i}_ADDR}\"
		eval len=\"\${CISCO_SPLIT_INC_${i}_MASKLEN}\"
		[ -n "$addr" ] && [ -n "$len" ] && echo "$addr/$len"
		i=$((i + 1))
	done
}

# route_to DEV NET: make NET leave through DEV, whether or not it exists yet.
# macOS: add first, change only when add failed because the exact route
# exists. Never change first: "route change" on a route that doesn't exist
# rewrites the best match instead, which is the default route.
route_to() {
	case "$OS" in
	Darwin)
		route -n add -net "$2" -interface "$1" >/dev/null 2>&1 ||
			route -n change -net "$2" -interface "$1" >/dev/null 2>&1
		;;
	*)
		ip route replace "$2" dev "$1" >/dev/null 2>&1
		;;
	esac
}

# route_drop_own DEV NET: remove NET only while it exists exactly and leaves
# through DEV. "route get" reports the best match, so the destination is
# checked too, or a broader route (the default) could be matched.
route_drop_own() {
	case "$OS" in
	Darwin)
		if route -n get -net "$2" 2>/dev/null | grep -q "^ *destination: ${2%/*}\$" &&
			route -n get -net "$2" 2>/dev/null | grep -q "interface: $1\$"; then
			route -n delete -net "$2" >/dev/null 2>&1
		fi
		;;
	*)
		ip route del "$2" dev "$1" >/dev/null 2>&1
		;;
	esac
}

# iface_exists DEV
iface_exists() {
	case "$OS" in
	Darwin) ifconfig "$1" >/dev/null 2>&1 ;;
	*) [ -d "/sys/class/net/$1" ] ;;
	esac
}

# json_list A B C -> ["A","B","C"]
json_list() {
	out=""
	for v in "$@"; do
		[ -n "$out" ] && out="$out,"
		out="$out\"$v\""
	done
	printf '[%s]' "$out"
}

write_state() {
	# shellcheck disable=SC2046
	routes=$(json_list $(pushed_routes))
	# shellcheck disable=SC2086
	dns=$(json_list $INTERNAL_IP4_DNS)
	printf '{"vpn":"%s","tundev":"%s","ip":"%s","gateway":"%s","dns":%s,"routes":%s,"at":"%s"}\n' \
		"$VPN" "$TUNDEV" "$INTERNAL_IP4_ADDRESS" "$VPNGATEWAY" "$dns" "$routes" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
		>"$STATE_FILE.tmp" && mv -f "$STATE_FILE.tmp" "$STATE_FILE"
	chmod 644 "$STATE_FILE" 2>/dev/null
}

# restore_others: after this tunnel's routes are gone, give every other VPN
# whose tunnel is still up its routes back (they may have been replaced by
# this session, or deleted by prefix by the system script).
restore_others() {
	for f in $STATE_GLOB; do
		[ -f "$f" ] || continue
		[ "$f" = "$STATE_FILE" ] && continue
		dev=$(sed -n 's/.*"tundev":"\([^"]*\)".*/\1/p' "$f")
		[ -n "$dev" ] && [ "$dev" != "$TUNDEV" ] && iface_exists "$dev" || continue
		for net in $(sed -n 's/.*"routes":\[\([^]]*\)\].*/\1/p' "$f" | tr ',' ' ' | tr -d '"'); do
			route_to "$dev" "$net"
		done
	done
}

[ -n "$TUNDEV" ] || exit 0

case "$reason" in
connect | reconnect)
	for net in $(pushed_routes); do
		route_to "$TUNDEV" "$net"
	done
	write_state
	;;
disconnect)
	for net in $(pushed_routes); do
		route_drop_own "$TUNDEV" "$net"
	done
	rm -f "$STATE_FILE" "$STATE_FILE.tmp"
	restore_others
	;;
esac
trace end
exit 0
`
